import { image } from "./graphic/images.js";

export const dataProduct = [
  {
    id: 1,
    title: "Product 1",
    price: "99999",
    amountPerSell: 1,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: "Category 1",
    featured: false,
    image: image,
    link: "https://youtube.com",
  },
  {
    id: 2,
    title: "Product 2",
    price: "99999",
    amountPerSell: 3,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: ["Category 2", "Category 1", "Category 6"],
    featured: true,
    image: image,
    link: "https://youtube.com",
  },
  {
    id: 3,
    title: "Product 3",
    price: "99999",
    amountPerSell: 1,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: "Category 3",
    featured: false,
    image: image,
    link: "https://youtube.com",
  },
  {
    id: 4,
    title: "Product 4",
    price: "99999",
    amountPerSell: 1,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: ["Category 1", "Category 4", "Category 2"],
    featured: true,
    image: image,
    link: "https://youtube.com",
  },
  {
    id: 5,
    title: "Product 5",
    price: "99999",
    amountPerSell: 1,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: ["Category 5", "Category 6"],
    featured: false,
    image: image,
    link: "https://youtube.com",
  },
  {
    id: 6,
    title: "Product 6",
    price: "99999",
    amountPerSell: 3,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: ["Category 6", "Category 7"],
    featured: true,
    image: image,
    link: "https://youtube.com",
  },
  {
    id: 7,
    title: "Product 7",
    price: "99999",
    amountPerSell: 1,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: "Category 7",
    featured: false,
    image: image,
    link: "https://youtube.com",
  },
  {
    id: 8,
    title: "Product 8",
    price: "99999",
    amountPerSell: 1,
    unit: "piece",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit",
    category: ["Category 4", "Category 5"],
    featured: true,
    image: image,
    link: "https://youtube.com",
  },
];
